/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/5vb7lhzJRo9
 */
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { useForm } from 'react-hook-form';

function AuthFormContainer({ children }: { children?: React.ReactNode }) {
  return (
    <div className="h-screen w-full flex items-center justify-center bg-gray-100 dark:bg-gray-900">
      <div className="grid lg:grid-cols-2 gap-5 sm:max-w-md lg:max-w-4xl w-full bg-white dark:bg-gray-800 shadow rounded-xl">
        <div className="flex flex-col justify-center p-8">{children}</div>
        <div className="hidden lg:block">
          <img
            alt="Login Image"
            className="w-full h-full object-cover rounded-r-xl"
            height="500"
            src="/images/splash.jpg"
            style={{
              aspectRatio: '500/500',
              objectFit: 'cover',
            }}
            width="500"
          />
        </div>
      </div>
    </div>
  );
}

export function LoginForm() {
  const form = useForm({
    defaultValues: {
      email: '',
      password: '',
    },
  });

  return (
    <AuthFormContainer>
      <div className="flex justify-center">
        <img
          alt="Logo"
          className="w-10 h-10"
          height="100"
          src="https://mikoto.io/logo.svg"
          style={{
            // fill the svg white
            filter: 'invert(100%)',
            opacity: 0.2,
            aspectRatio: '100/100',
            objectFit: 'cover',
          }}
          width="100"
        />
      </div>
      <h2 className="mt-6 text-center text-3xl font-semibold text-gray-900 dark:text-white">
        Welcome Back!
      </h2>
      <p className="mt-2 text-center text-sm text-gray-600 dark:text-gray-200">
        Please login to your account.
      </p>
      <form
        className="mt-8 flex flex-col space-y-3"
        onSubmit={form.handleSubmit((data) => {
          console.log(data);
        })}
      >
        <div className="space-y-2">
          <Label htmlFor="email">Email</Label>
          <Input
            id="email"
            placeholder="misakamikoto@mikoto.io"
            required
            type="email"
            {...form.register('email')}
          />
        </div>
        <div className="space-y-2">
          <div className="flex items-center">
            <Label htmlFor="password">Password</Label>
            <Link
              className="ml-auto text-sm text-gray-500 dark:text-gray-400 underline"
              href="/forgotpassword"
            >
              Forgot password?
            </Link>
          </div>
          <Input
            id="password"
            required
            type="password"
            {...form.register('password')}
          />
        </div>
        <div className="flex items-center justify-between">
          <Button
            className="w-full py-2 px-4 bg-blue-600 text-white rounded-md hover:bg-blue-700"
            type="submit"
          >
            Login
          </Button>
        </div>
        <div className="text-center">
          <span className="text-sm text-gray-600 dark:text-gray-200">
            Don't have an account?
          </span>
          <Link className="text-sm text-blue-600 underline ml-1" href="/signup">
            Sign Up
          </Link>
        </div>
      </form>
    </AuthFormContainer>
  );
}
